CREATE TABLE payment_attempts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    payment_attempt_id VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    payment_method VARCHAR(32) NOT NULL,
    payment_scheme VARCHAR(64) NOT NULL,
    store_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    table_session_id BIGINT NOT NULL,
    session_ref VARCHAR(64) NOT NULL,
    settlement_amount_cents BIGINT NOT NULL,
    currency_code VARCHAR(8) NOT NULL,
    provider_payment_id VARCHAR(128) NULL,
    provider_checkout_url VARCHAR(512) NULL,
    provider_status VARCHAR(64) NULL,
    attempt_status VARCHAR(32) NOT NULL,
    webhook_event_type VARCHAR(128) NULL,
    last_webhook_payload_json LONGTEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    completed_at DATETIME(6) NULL,
    UNIQUE KEY uk_payment_attempts_payment_attempt_id (payment_attempt_id),
    KEY idx_payment_attempts_provider_payment_id (provider, provider_payment_id),
    KEY idx_payment_attempts_table (store_id, table_id, attempt_status)
);
